import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN: str = os.getenv("BOT_TOKEN", "")
DATABASE_URL: str = os.getenv("DATABASE_URL", "sqlite+aiosqlite:///./sea_of_shadows.db")
ADMIN_IDS: list[int] = [
    int(x) for x in os.getenv("ADMIN_IDS", "").split(",") if x.strip()
]
LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")

# Game constants
MAX_LEVEL = 100
MAX_FLEET_SIZE = 5
MAX_INVENTORY_SIZE = 100
MAX_GUILD_MEMBERS = 50
MAX_ENERGY = 100
STARTING_GOLD = 500
STARTING_ISLAND = "port_royal"
XP_PER_LEVEL_BASE = 100
XP_PER_LEVEL_MULTIPLIER = 1.15
ENERGY_MAX = 100
ENERGY_REGEN_MINUTES = 5
DAILY_QUEST_COUNT = 3
AUCTION_FEE_PERCENT = 5
TRADE_TAX_PERCENT = 3
PVP_MIN_LEVEL = 10
PVP_RATING_K = 32
PVP_GOLD_REWARD = 100
PVP_XP_REWARD = 50
GUILD_CREATE_COST = 5000
GUILD_CREATION_COST = 5000
SMUGGLING_RISK_BASE = 0.3
WEATHER_CHANGE_HOURS = 4
EVENT_CHECK_MINUTES = 30
CRITICAL_HIT_MULTIPLIER = 1.5
BASE_CRIT_CHANCE = 0.1
BASE_DODGE_CHANCE = 0.05
